name: Dịch file YAML

on:
  issues:
    types: [opened, reopened]

jobs:
  dich-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tải file YAML
        id: tai-file
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const fileContent = await github.rest.issues.getIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            }).then(response => response.data.body);

            const yamlContent = fileContent.match(/`yaml\n([\s\S]*?)`/)[1];
            core.setOutput('yamlContent', yamlContent);

      - name: Dịch file YAML
        id: dich-file
        uses: ShadowCrafter011/YAML-Translator@v1
        with:
          source_language: 'vi'
          target_language: 'en'
          yaml_content: ${{ steps.tai-file.outputs.yamlContent }}

      - name: Tạo file YAML dịch
        uses: actions/upload-artifact@v3
        with:
          name: yaml-dich
          path: ${{ steps.dich-file.outputs.translatedYaml }}

      - name: Thông báo hoàn thành
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: 'File YAML đã được dịch và tải lên thành công!'
            });
